rule gtdbtk_gather_matches:
    """
    this rule require the gtdbtk databases. The tool finds the database by 
    using a path specified in a file in the environment. I predownloaded the 
    databases and placed them in the required location.
    The path is in this file:
    .snakemake/conda/1261315d/etc/conda/activate.d/gtdbtk.sh
    """
    input: "genomes"
    output: directory("outputs/gtdbtk/")
    params:  outdir = "outputs/gtdbtk"
    conda: "env-gtdbtk.yml"
    shell:'''
    gtdbtk classify_wf --genome_dir {input} --out_dir {params.outdir} --cpus 8 --extension fna.gz
    '''
